SET FOREIGN_KEY_CHECKS = 0;
SET SQL_SAFE_UPDATES = 0;
SET GLOBAL log_bin_trust_function_creators = 1;

DELETE FROM Person;
DELETE FROM Advisor;
DELETE FROM Class;
DELETE FROM Course;
DELETE FROM Department;
DELETE FROM Grade;
DELETE FROM Instructor;
DELETE FROM InstructorDepartment;
DELETE FROM Prerequisite;
DELETE FROM Program;
DELETE FROM ResearchFunding;
DELETE FROM Section;
DELETE FROM Student;
DELETE FROM StudentAdvisor;
DELETE FROM StudentDepartment;
DELETE FROM StudentProgram;
DELETE FROM Supervisor;
DELETE FROM StudentSupervisor;
DELETE FROM Term;
DELETE FROM Campus;
DELETE FROM Building;
DELETE FROM Room;
DELETE FROM Facilities;
DELETE FROM Address;
DELETE FROM StudentPastDegrees;
DELETE FROM IndustryExperience;
DELETE FROM Contract;
DELETE FROM Salary;
DELETE FROM Publications;
DELETE FROM Awards;
DELETE FROM TA_Assignments;
DELETE FROM ResearchFunding;
DELETE FROM Func;